# Generated by Django 6.0.2 on 2026-02-05 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='function',
            field=models.CharField(blank=True, choices=[('PRESIDENT', 'President'), ('VICE_P', 'Vice President'), ('SEC', 'Secretaire'), ('COM', 'Chargé a la communication'), ('Num', 'Chargé au numérique'), ('ACOM', 'Chargé adjoint a la communication'), ('ANum', 'Chargé adjoint au numérique')], max_length=100, null=True),
        ),
    ]
