# Generated by Django 6.0.2 on 2026-02-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_function'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='function',
            field=models.CharField(blank=True, choices=[('PRESIDENT', 'President'), ('VICE_P', 'Vice President'), ('SEC', 'Secretaire'), ('COM', 'Chargé a la communication'), ('NUM', 'Chargé au numérique'), ('ACOM', 'Chargé adjoint a la communication'), ('ANUM', 'Chargé adjoint au numérique')], max_length=100, null=True),
        ),
    ]
