# Generated by Django 6.0.2 on 2026-02-06 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('departement', models.CharField(choices=[('BA', 'Business Administration'), ('G.CIVIL', 'Génie Civil'), ('BTS', 'BTS'), ('SEG', 'Sciences Economiques et Gestion'), ('GLT', 'Génie Logiciel et Transport'), ('D', 'Droit'), ('G.I', 'Génie Informatique'), ('JC', 'Journalisme et Communication')], max_length=20)),
                ('level', models.CharField(choices=[('L1', 'L1'), ('L2', 'L2'), ('L3', 'L3'), ('L4', 'L4'), ('L5', 'L5')], max_length=2)),
                ('message_type', models.CharField(choices=[('SUG', 'Suggestion'), ('PLT', 'Plainte'), ('RMQ', 'Remarque')], max_length=3)),
                ('content', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
